# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

# Blog seeds — generated by the blog template.
# Remove or update credentials before sharing this file.

admin = User.find_or_create_by!(email_address: "mrobe18@gmail.com") do |u|
  u.password = "!MaLeRo3169!"
  u.admin    = true
end
puts "Admin: #{admin.email_address}"

featured = Post.find_or_create_by!(title: "Welcome to the Blog") do |p|
  p.subtitle     = "A fresh start — edit or replace this from the admin dashboard."
  p.body         = "<p>This is your featured post. Sign in at <strong>/session/new</strong> to manage your content.</p>"
  p.featured     = true
  p.published_at = Time.current
  p.user         = admin
end

3.times do |i|
  Post.find_or_create_by!(title: "Sample Post #{i + 1}") do |p|
    p.subtitle     = "A short description for sample post #{i + 1}."
    p.body         = "<p>Replace this with your own writing.</p>"
    p.published_at = (i + 1).days.ago
    p.user         = admin
  end
end

puts "Posts: #{Post.count} total"
